train:
  seq_length: 40
  epochs: 500
  total_steps: 10000
  batch_size: 8

  checkpoint_interval: 10000
  checkpoint_dir: "/home/charlie/gpt4_reward_model.py/trlx/checkpoints"
  eval_interval: 16

  pipeline: "PromptPipeline"
  orchestrator: "T5PPOOrchestrator"

model:
  model_type: "T5AcceleratePPOModel"
  model_path: "google/flan-t5-small"
  tokenizer_path: "google/flan-t5-small"

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 10000 # train.total_steps
    eta_min: 1.0e-4

method:
  name: "ppoconfig"
  num_rollouts: 16
  chunk_size: 16
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 0.06
  horizon: 10000
  gamma: 0.99
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1.0
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 40
    top_k: 0
    top_p: 1.0
    do_sample: True